Create docker image

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,10 +1,24 @@
 name: Main workflow
 on: push
+env:
+  github_username: ${{ github.actor }}
+  github_password: ${{ secrets.GITHUB_TOKEN }}
+  GIT_COMMIT: ${{ github.sha }}
 jobs:
   Build:
     runs-on: ubuntu-latest
     container: gradle:6-jdk11
     steps:
+      - name: Validate Docker username is all lowercase
+        id: validate_lower
+        run: |
+          if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+            echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+            exit 1
+          else
+            echo "Docker username format is valid."
+          fi
+        shell: bash
       - name: Clone down repository
         uses: actions/checkout@v4       
       - name: Build application
@@ -32,3 +46,18 @@ jobs:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DISABLE_ERRORS: true
+  Docker-image:
+    runs-on: ubuntu-latest
+    needs: [Build]
+    permissions:
+      packages: write
+    steps:
+      - name: Download code
+        uses: actions/download-artifact@v4
+        with:
+          name: code
+          path: .
+      - name: build docker
+        run: bash ci/build-docker.sh
+      - name: push docker
+        run: bash ci/push-docker.sh
